FROM ubuntu:latest

# Mise à jour du système et installation des dépendances nécessaires
RUN apt-get update && apt-get install -y \
    build-essential \
    cpanminus \
    libdbi-perl \
    libset-intervaltree-perl \
    libwww-perl \
    libhttp-daemon-perl \
    git \
    libdbd-mysql-perl

# Installation des modules Perl requis
RUN cpanm Module::Build \
    && cpanm DBI \
    && cpanm Set::IntervalTree \
    && cpanm LWP::Simple \
    && cpanm HTTP::Daemon \
    && cpanm Test::Needs
    # && cpanm DBD-mysql

# Clone du dépôt ensembl-vep
RUN git clone https://github.com/Ensembl/ensembl-vep.git

# Définition du répertoire de travail
WORKDIR /ensembl-vep

# Installation de VEP
RUN ./INSTALL.pl -a cfp -n -s "homo_sapiens_vep" --ASSEMBLY GRCh38 --PLUGINS list

# Commande par défaut à exécuter lorsque le conteneur démarre
CMD ["/bin/bash"]
