# Utilisation d'une image de base
FROM ubuntu

RUN apt-get update && apt-get install --no-install-recommends -y \
    libncurses5-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-gnutls-dev \
    zlib1g-dev \
    libssl-dev \
    gcc \
    wget \
    make \
    perl \
    bzip2 \
    gnuplot \
    ca-certificates \
    gawk && \
    apt-get autoclean && rm -rf /var/lib/apt/lists/*

###### INSTALLATIONS DE SAMTOOLS ######
ARG SAMTOOLSVER=1.13

RUN wget https://github.com/samtools/samtools/releases/download/${SAMTOOLSVER}/samtools-${SAMTOOLSVER}.tar.bz2 && \
    tar -xjf samtools-${SAMTOOLSVER}.tar.bz2 && \
    rm samtools-${SAMTOOLSVER}.tar.bz2 && \
    cd samtools-${SAMTOOLSVER} && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf samtools-${SAMTOOLSVER} && \
    mkdir /data

RUN apt-get update && apt-get install -y git


# Création du répertoire "projet"
RUN mkdir /github

RUN mkdir /output 

WORKDIR /github

# Cloner le référentiel GitHub et copier son contenu dans le répertoire "projet"
RUN git clone https://github.com/yguiberteau/Pipeline-pour-l-analyse-des-maladies-mitochondriales.git /tmp/repo && \
    cp -r /tmp/repo/* /github && \
    rm -rf /tmp/repo

# Création du fichier "benzinzin.txt"
RUN echo "Contenu du fichier benzinzin.txt" > /data/benzinzin.txt


# Copier le fichier FASTQ dans le conteneur
COPY IonXpress_011.fastq /data/IonXpress_011.fastq

# Exécuter le script script1.sh

# Instruction CMD pour exécuter une commande par défaut lorsque le conteneur est démarré
CMD tail -f /dev/null


